### ISSUE TITLE
Добавить скрипт/инструкцию по установке программы

### ISSUE THREAD

**Issue by Vascom** [matimatik/fbless#26]
Добавьте, пожалуйста скрипт или инстркуцию для установки программы в файловую систему. Это позволит опакетить и нормально устанавливать/удалять.

**Comment by btimofeev** [comment]
В корне лежит setup.py

Судя по документации устанавливается командой:
`python setup.py install`

Либо в определенную директорию:
`python setup.py install --prefix=/usr/local`

**Comment by btimofeev** [comment]
Поправка: в билд скрипте [archlinux](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fbless) делается командой:
`python2 setup.py install --root=$pkgdir`

Скорее всего это более правильный метод, по сравнению с --prefix.

**Comment by Vascom** [comment]
Хорошо, надо попробовать.

**Comment by Vascom** [comment]
Да, всё работает.
